services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8081:8081"
    depends_on:
      - backend

volumes:
  db_data:
