spring.application.name=ticket-guru
spring.data.rest.basePath=/api
jwt.expiration=3600000
jwt.secret=${JWT_SECRET}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=prod
